### PR TITLE
Proposition to detail and simplify the Main example.

### PR DESCRIPTION
**Pull request by mpizenberg**
Hi !

First, I would like to thank you for this package.
I was about to create one to deal with throttle since I had only found debouncing packages before.
And then, looking more into the details of your code
(since it was very similar to what I had in mind) I realized that this also deals with throttle.

After playing a bit with the code of the Main.elm example,
I modified it a bit (diffs look big because of elm-format mainly) to make it
clearer (at least I think so) while pointing to other features in comments.

Could you tell me what you think of it ?

In sum, the proposed modifications are the following:
* use elm-format to format the code automatically.
* not exposing(..) in imports to avoid confusion.
* adding multiple comments.
* remove unused subscriptions.
* remove the model value attribute that is not used.
* remove the unused NoOp Msg.
* keep Msg order in update (Input -> Saved -> DebounceMsg).
* replace "s" by "string" for readability.
* replace "msg" by "debounceMsg" in DebounceMsg case to avoid confusion.

### CODE REVIEW

**Comment by jinjor** [comment]
Thank you for PR!

Looks good but I want keep it simple and compact. Does it need to mention `Save` and `report` which is not relevant to this library? Do you want to know `takeLast` and `takeAll` here?

So I'm curious what really lacks in the document(= API and examples). What was the hardest parts for you to understand? I would really appreciate if you focus on it (not trying to make everything better).

**Comment by mpizenberg** [comment]
Ok, so I think the main issue is the entry cost. I will detail a bit what I mean. When I first found your package in elm packages, I wasn't really attracted by the home page documentation (that corresponds to the readme). There is a big block of code and, as a user, you don't understand what corresponds to the added code for the debouncing. From a user point of view, what you would like to know (IMHO) is how to transform your initial code so that it deals with debouncing. You might give a look at [this debouncing package][bcardiff] for ideas.

But I was intrigued about what where doing the "strategies" so I tried the example linked.
In the example, the first thing I noticed is that there were lots of things unused (subscriptions, the value attribute in the model, the NoOp message) in the code, that clouded the important parts.
And regarding the comments I added, you are right, it is a bit too much. I think I added them in a bit of eagerness because I did not find a place where this was explained before. The right place for these would be in the documentation home page. This example should be kept simple. But in my defense, even with all the added comment, the PR is only 10 lines more than the original file (since I removed some stuff also).

For your question about `Save` and `report`, you should keep `Save` since it is were you handle the debounced value but get rid of `report`. Just store the current debounced signal. Plus this report list might be confused with the `takeAll` option which has nothing to do with it.

As for the elm-format thing, sorry it is automatic with my editor (could deactivate it but prefer not to).
You should give it a try though. Especially when publishing packages, since it enables an objective formatting of the code (I think it is a good thing when multiple persons work on the same code).

Well, in sum, this PR has been done maybe in too much eagerness and I don't matter at all if you close it.

Also, don't hesitate to peak at the code of [this repo][mpizenberg] (branch throttle) for ideas. It is a personal fork of the other package I mentioned earlier. I added the throttle behavior and upgraded it to elm 0.18. It is not on Elm packages though.

[bcardiff]: http://package.elm-lang.org/packages/bcardiff/elm-debounce/latest/Debounce
[mpizenberg]: https://github.com/mpizenberg/elm-debounce/tree/throttle

**Comment by jinjor** [comment]
Oh, wait. Did you see [this demo](https://jinjor.github.io/elm-debounce/)? Is this not linked from anywhere?

**Comment by mpizenberg** [comment]
What do you mean by "see this demo" ?
I mean, I have tried it of course since this is the example I modified and made a PR, but I have not seen anywhere a link to this online page no.

**Comment by jinjor** [comment]
Ah okay, it should be linked. Will do it.

I mean, I was wondering why you had to read the entire source (including `value`, `Save` and `report`) to understand the usage. I assume readers only read the commented code. Do you think this online demo could help?

**Comment by mpizenberg** [comment]
I think this can help understanding the use case if people do not know about debouncing or throttle, but not the usage. Usage implies how to use this package. For that, just a block code cannot replace documented narrative. Plus the code you give in package home page is not complete since you don't know what the `Debounce.update` call does. Specifically, I had no idea what was doing the `Debounce.takeLast save`.

**Comment by jinjor** [comment]
> Plus the code you give in package home page is not complete since you don't know what the Debounce.update call does. Specifically, I had no idea what was doing the Debounce.takeLast save.

Fair point, but I don't think it's good idea to explain all about the example *app*, TEA and API details.

I made another plan at #2. How do you feel?

**Pull request closed without merging**
